# Generated by Django 4.2.7 on 2023-11-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wgs_app", "0002_referreddb_age_referreddb_amc_nd20_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referreddb",
            name="sample_name",
            field=models.CharField(
                blank=True, default=None, max_length=100, null=True, unique=True
            ),
        ),
    ]
