# Generated by Django 4.2.7 on 2023-11-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wgs_app", "0003_alter_referreddb_sample_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="referreddb",
            name="diagnosis",
            field=models.CharField(blank=True, default=None, max_length=111, null=True),
        ),
        migrations.AddField(
            model_name="referreddb",
            name="growth",
            field=models.CharField(blank=True, default=None, max_length=119, null=True),
        ),
        migrations.AddField(
            model_name="referreddb",
            name="otherab1_disk",
            field=models.CharField(blank=True, default=None, max_length=354, null=True),
        ),
        migrations.AddField(
            model_name="referreddb",
            name="otherab1_disk_ris",
            field=models.CharField(blank=True, default=None, max_length=355, null=True),
        ),
        migrations.AddField(
            model_name="referreddb",
            name="otherab1_mic",
            field=models.CharField(blank=True, default=None, max_length=356, null=True),
        ),
        migrations.AddField(
            model_name="referreddb",
            name="otherab1_mic_ris",
            field=models.CharField(blank=True, default=None, max_length=357, null=True),
        ),
        migrations.AddField(
            model_name="referreddb",
            name="otherab1_name",
            field=models.CharField(blank=True, default=None, max_length=353, null=True),
        ),
        migrations.AddField(
            model_name="referreddb",
            name="otherab2_disk",
            field=models.CharField(blank=True, default=None, max_length=359, null=True),
        ),
        migrations.AddField(
            model_name="referreddb",
            name="otherab2_disk_ris",
            field=models.CharField(blank=True, default=None, max_length=360, null=True),
        ),
        migrations.AddField(
            model_name="referreddb",
            name="otherab2_mic",
            field=models.CharField(blank=True, default=None, max_length=361, null=True),
        ),
        migrations.AddField(
            model_name="referreddb",
            name="otherab2_mic_ris",
            field=models.CharField(blank=True, default=None, max_length=362, null=True),
        ),
        migrations.AddField(
            model_name="referreddb",
            name="otherab2_name",
            field=models.CharField(blank=True, default=None, max_length=358, null=True),
        ),
        migrations.AddField(
            model_name="referreddb",
            name="otherab3_disk",
            field=models.CharField(blank=True, default=None, max_length=364, null=True),
        ),
        migrations.AddField(
            model_name="referreddb",
            name="otherab3_disk_ris",
            field=models.CharField(blank=True, default=None, max_length=365, null=True),
        ),
        migrations.AddField(
            model_name="referreddb",
            name="otherab3_mic",
            field=models.CharField(blank=True, default=None, max_length=366, null=True),
        ),
        migrations.AddField(
            model_name="referreddb",
            name="otherab3_mic_ris",
            field=models.CharField(blank=True, default=None, max_length=367, null=True),
        ),
        migrations.AddField(
            model_name="referreddb",
            name="otherab3_name",
            field=models.CharField(blank=True, default=None, max_length=363, null=True),
        ),
        migrations.AddField(
            model_name="referreddb",
            name="otherab4_disk",
            field=models.CharField(blank=True, default=None, max_length=369, null=True),
        ),
        migrations.AddField(
            model_name="referreddb",
            name="otherab4_disk_ris",
            field=models.CharField(blank=True, default=None, max_length=370, null=True),
        ),
        migrations.AddField(
            model_name="referreddb",
            name="otherab4_mic",
            field=models.CharField(blank=True, default=None, max_length=371, null=True),
        ),
        migrations.AddField(
            model_name="referreddb",
            name="otherab4_mic_ris",
            field=models.CharField(blank=True, default=None, max_length=372, null=True),
        ),
        migrations.AddField(
            model_name="referreddb",
            name="otherab4_name",
            field=models.CharField(blank=True, default=None, max_length=368, null=True),
        ),
        migrations.AddField(
            model_name="referreddb",
            name="otherab5_disk",
            field=models.CharField(blank=True, default=None, max_length=374, null=True),
        ),
        migrations.AddField(
            model_name="referreddb",
            name="otherab5_disk_ris",
            field=models.CharField(blank=True, default=None, max_length=375, null=True),
        ),
        migrations.AddField(
            model_name="referreddb",
            name="otherab5_mic",
            field=models.CharField(blank=True, default=None, max_length=376, null=True),
        ),
        migrations.AddField(
            model_name="referreddb",
            name="otherab5_mic_ris",
            field=models.CharField(blank=True, default=None, max_length=377, null=True),
        ),
        migrations.AddField(
            model_name="referreddb",
            name="otherab5_name",
            field=models.CharField(blank=True, default=None, max_length=373, null=True),
        ),
        migrations.AddField(
            model_name="referreddb",
            name="service_type",
            field=models.CharField(blank=True, default=None, max_length=114, null=True),
        ),
        migrations.AddField(
            model_name="referreddb",
            name="urine_colct",
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="amc_nd20",
            field=models.CharField(blank=True, default=None, max_length=137, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="amc_nd20_ris",
            field=models.CharField(blank=True, default=None, max_length=138, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="amc_nm",
            field=models.CharField(blank=True, default=None, max_length=139, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="amc_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="amk_nd30",
            field=models.CharField(blank=True, default=None, max_length=133, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="amk_nd30_ris",
            field=models.CharField(blank=True, default=None, max_length=134, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="amk_nm",
            field=models.CharField(blank=True, default=None, max_length=135, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="amk_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=136, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="amp_nd10",
            field=models.CharField(blank=True, default=None, max_length=141, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="amp_nd10_ris",
            field=models.CharField(blank=True, default=None, max_length=142, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="amp_nm",
            field=models.CharField(blank=True, default=None, max_length=143, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="amp_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=144, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="ampc",
            field=models.CharField(blank=True, default=None, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="arsrl_org",
            field=models.CharField(blank=True, default=None, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="arsrl_post",
            field=models.CharField(blank=True, default=None, max_length=124, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="arsrl_pre",
            field=models.CharField(blank=True, default=None, max_length=121, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="atm_nd30",
            field=models.CharField(blank=True, default=None, max_length=149, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="atm_nd30_ris",
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="atm_nm",
            field=models.CharField(blank=True, default=None, max_length=151, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="atm_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=152, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="azm_nd15",
            field=models.CharField(blank=True, default=None, max_length=153, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="azm_nd15_ris",
            field=models.CharField(blank=True, default=None, max_length=154, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="azm_nm",
            field=models.CharField(blank=True, default=None, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="azm_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=156, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="bl",
            field=models.CharField(blank=True, default=None, max_length=129, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="carb",
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="caz_nd30",
            field=models.CharField(blank=True, default=None, max_length=185, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="caz_nd30_ris",
            field=models.CharField(blank=True, default=None, max_length=186, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="caz_nm",
            field=models.CharField(blank=True, default=None, max_length=187, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="caz_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=188, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cec_nd30",
            field=models.CharField(blank=True, default=None, max_length=157, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cec_nd30_ris",
            field=models.CharField(blank=True, default=None, max_length=158, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cec_nm",
            field=models.CharField(blank=True, default=None, max_length=159, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cec_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cep_nd30",
            field=models.CharField(blank=True, default=None, max_length=197, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cep_nd30_ris",
            field=models.CharField(blank=True, default=None, max_length=198, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cep_nm",
            field=models.CharField(blank=True, default=None, max_length=199, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cep_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cfm_nd5",
            field=models.CharField(blank=True, default=None, max_length=169, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cfm_nd5_ris",
            field=models.CharField(blank=True, default=None, max_length=170, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cfm_nm",
            field=models.CharField(blank=True, default=None, max_length=171, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cfm_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=172, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cfp_nd75",
            field=models.CharField(blank=True, default=None, max_length=173, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cfp_nd75_ris",
            field=models.CharField(blank=True, default=None, max_length=174, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cfp_nm",
            field=models.CharField(blank=True, default=None, max_length=175, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cfp_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=176, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="chl_nd30",
            field=models.CharField(blank=True, default=None, max_length=201, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="chl_nd30_ris",
            field=models.CharField(blank=True, default=None, max_length=202, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="chl_nm",
            field=models.CharField(blank=True, default=None, max_length=203, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="chl_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=204, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cip_nd5",
            field=models.CharField(blank=True, default=None, max_length=205, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cip_nd5_ris",
            field=models.CharField(blank=True, default=None, max_length=206, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cip_nm",
            field=models.CharField(blank=True, default=None, max_length=207, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cip_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=208, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cli_nd2",
            field=models.CharField(blank=True, default=None, max_length=209, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cli_nd2_ris",
            field=models.CharField(blank=True, default=None, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cli_nm",
            field=models.CharField(blank=True, default=None, max_length=211, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cli_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=212, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="col_nd10",
            field=models.CharField(blank=True, default=None, max_length=333, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="col_nd10_ris",
            field=models.CharField(blank=True, default=None, max_length=334, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="col_nm",
            field=models.CharField(blank=True, default=None, max_length=335, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="col_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=336, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cro_nd30",
            field=models.CharField(blank=True, default=None, max_length=189, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cro_nd30_ris",
            field=models.CharField(blank=True, default=None, max_length=190, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cro_nm",
            field=models.CharField(blank=True, default=None, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cro_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=192, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="ctx_nd30",
            field=models.CharField(blank=True, default=None, max_length=177, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="ctx_nd30_ris",
            field=models.CharField(blank=True, default=None, max_length=178, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="ctx_nm",
            field=models.CharField(blank=True, default=None, max_length=179, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="ctx_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cxa_nd30",
            field=models.CharField(blank=True, default=None, max_length=193, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cxa_nd30_ris",
            field=models.CharField(blank=True, default=None, max_length=194, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cxa_nm",
            field=models.CharField(blank=True, default=None, max_length=195, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="cxa_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=196, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="czo_nd30",
            field=models.CharField(blank=True, default=None, max_length=161, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="czo_nd30_ris",
            field=models.CharField(blank=True, default=None, max_length=162, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="czo_nm",
            field=models.CharField(blank=True, default=None, max_length=163, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="czo_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=164, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="dap_nd30",
            field=models.CharField(blank=True, default=None, max_length=349, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="dap_nd30_ris",
            field=models.CharField(blank=True, default=None, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="dap_nm",
            field=models.CharField(blank=True, default=None, max_length=351, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="dap_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=352, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="diagnosis_icd10",
            field=models.CharField(blank=True, default=None, max_length=112, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="dor_nd10",
            field=models.CharField(blank=True, default=None, max_length=329, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="dor_nd10_ris",
            field=models.CharField(blank=True, default=None, max_length=330, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="dor_nm",
            field=models.CharField(blank=True, default=None, max_length=331, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="dor_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=332, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="ery_nd15",
            field=models.CharField(blank=True, default=None, max_length=217, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="ery_nd15_ris",
            field=models.CharField(blank=True, default=None, max_length=218, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="ery_nm",
            field=models.CharField(blank=True, default=None, max_length=219, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="ery_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="esbl",
            field=models.CharField(blank=True, default=None, max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="etp_nd10",
            field=models.CharField(blank=True, default=None, max_length=325, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="etp_nd10_ris",
            field=models.CharField(blank=True, default=None, max_length=326, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="etp_nm",
            field=models.CharField(blank=True, default=None, max_length=327, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="etp_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=328, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="fep_nd30",
            field=models.CharField(blank=True, default=None, max_length=165, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="fep_nd30_ris",
            field=models.CharField(blank=True, default=None, max_length=166, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="fep_nm",
            field=models.CharField(blank=True, default=None, max_length=167, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="fep_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=168, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="fox_nd30",
            field=models.CharField(blank=True, default=None, max_length=181, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="fox_nd30_ris",
            field=models.CharField(blank=True, default=None, max_length=182, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="fox_nm",
            field=models.CharField(blank=True, default=None, max_length=183, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="fox_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=184, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="geh_nd120",
            field=models.CharField(blank=True, default=None, max_length=309, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="geh_nd120_ris",
            field=models.CharField(blank=True, default=None, max_length=310, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="geh_nm",
            field=models.CharField(blank=True, default=None, max_length=311, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="geh_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=312, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="gen_nd10",
            field=models.CharField(blank=True, default=None, max_length=221, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="gen_nd10_ris",
            field=models.CharField(blank=True, default=None, max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="gen_nm",
            field=models.CharField(blank=True, default=None, max_length=223, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="gen_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=224, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="icr",
            field=models.CharField(blank=True, default=None, max_length=132, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="ipm_nd10",
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="ipm_nd10_ris",
            field=models.CharField(blank=True, default=None, max_length=226, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="ipm_nm",
            field=models.CharField(blank=True, default=None, max_length=227, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="ipm_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=228, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="kan_nd30",
            field=models.CharField(blank=True, default=None, max_length=229, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="kan_nd30_ris",
            field=models.CharField(blank=True, default=None, max_length=230, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="kan_nm",
            field=models.CharField(blank=True, default=None, max_length=231, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="kan_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=232, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="lev_nd5",
            field=models.CharField(blank=True, default=None, max_length=233, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="lev_nd5_ris",
            field=models.CharField(blank=True, default=None, max_length=234, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="lev_nm",
            field=models.CharField(blank=True, default=None, max_length=235, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="lev_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=236, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="lnz_nd30",
            field=models.CharField(blank=True, default=None, max_length=317, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="lnz_nd30_ris",
            field=models.CharField(blank=True, default=None, max_length=318, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="lnz_nm",
            field=models.CharField(blank=True, default=None, max_length=319, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="lnz_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=320, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="mbl",
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="meca",
            field=models.CharField(blank=True, default=None, max_length=131, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="mem_nd10",
            field=models.CharField(blank=True, default=None, max_length=301, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="mem_nd10_ris",
            field=models.CharField(blank=True, default=None, max_length=302, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="mem_nm",
            field=models.CharField(blank=True, default=None, max_length=303, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="mem_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=304, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="mfx_nd5",
            field=models.CharField(blank=True, default=None, max_length=297, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="mfx_nd5_ris",
            field=models.CharField(blank=True, default=None, max_length=298, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="mfx_nm",
            field=models.CharField(blank=True, default=None, max_length=299, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="mfx_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="mno_nd30",
            field=models.CharField(blank=True, default=None, max_length=345, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="mno_nd30_ris",
            field=models.CharField(blank=True, default=None, max_length=346, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="mno_nm",
            field=models.CharField(blank=True, default=None, max_length=347, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="mno_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=348, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="mr",
            field=models.CharField(blank=True, default=None, max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="nal_nd30",
            field=models.CharField(blank=True, default=None, max_length=237, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="nal_nd30_ris",
            field=models.CharField(blank=True, default=None, max_length=238, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="nal_nm",
            field=models.CharField(blank=True, default=None, max_length=239, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="nal_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="nit_nd300",
            field=models.CharField(blank=True, default=None, max_length=241, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="nit_nd300_ris",
            field=models.CharField(blank=True, default=None, max_length=242, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="nit_nm",
            field=models.CharField(blank=True, default=None, max_length=243, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="nit_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=244, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="nor_nd10",
            field=models.CharField(blank=True, default=None, max_length=245, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="nor_nd10_ris",
            field=models.CharField(blank=True, default=None, max_length=246, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="nor_nm",
            field=models.CharField(blank=True, default=None, max_length=247, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="nor_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=248, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="nov_nd5",
            field=models.CharField(blank=True, default=None, max_length=321, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="nov_nd5_ris",
            field=models.CharField(blank=True, default=None, max_length=322, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="nov_nm",
            field=models.CharField(blank=True, default=None, max_length=323, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="nov_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=324, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="ofl_nd5",
            field=models.CharField(blank=True, default=None, max_length=249, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="ofl_nd5_ris",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="ofl_nm",
            field=models.CharField(blank=True, default=None, max_length=251, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="ofl_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="organism_code",
            field=models.CharField(blank=True, default=None, max_length=123, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="oxa_nd1",
            field=models.CharField(blank=True, default=None, max_length=253, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="oxa_nd1_ris",
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="oxa_nm",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="oxa_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="pen_nd10",
            field=models.CharField(blank=True, default=None, max_length=257, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="pen_nd10_ris",
            field=models.CharField(blank=True, default=None, max_length=258, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="pen_nm",
            field=models.CharField(blank=True, default=None, max_length=259, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="pen_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=260, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="pip_nd100",
            field=models.CharField(blank=True, default=None, max_length=261, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="pip_nd100_ris",
            field=models.CharField(blank=True, default=None, max_length=262, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="pip_nm",
            field=models.CharField(blank=True, default=None, max_length=263, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="pip_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="pol_nd300",
            field=models.CharField(blank=True, default=None, max_length=337, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="pol_nd300_ris",
            field=models.CharField(blank=True, default=None, max_length=338, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="pol_nm",
            field=models.CharField(blank=True, default=None, max_length=339, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="pol_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=340, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="qda_nd15",
            field=models.CharField(blank=True, default=None, max_length=341, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="qda_nd15_ris",
            field=models.CharField(blank=True, default=None, max_length=342, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="qda_nm",
            field=models.CharField(blank=True, default=None, max_length=343, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="qda_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=344, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="reason",
            field=models.CharField(blank=True, default=None, max_length=118, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="rif_nd5",
            field=models.CharField(blank=True, default=None, max_length=265, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="rif_nd5_ris",
            field=models.CharField(blank=True, default=None, max_length=266, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="rif_nm",
            field=models.CharField(blank=True, default=None, max_length=267, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="rif_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=268, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="sam_nd10",
            field=models.CharField(blank=True, default=None, max_length=145, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="sam_nd10_ris",
            field=models.CharField(blank=True, default=None, max_length=146, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="sam_nm",
            field=models.CharField(blank=True, default=None, max_length=147, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="sam_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=148, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="spe_nd100",
            field=models.CharField(blank=True, default=None, max_length=269, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="spe_nd100_ris",
            field=models.CharField(blank=True, default=None, max_length=270, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="spe_nm",
            field=models.CharField(blank=True, default=None, max_length=271, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="spe_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=272, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="spec_date",
            field=models.CharField(blank=True, default=None, max_length=116, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="spec_num",
            field=models.CharField(blank=True, default=None, max_length=115, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="spec_type",
            field=models.CharField(blank=True, default=None, max_length=117, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="sth_nd300",
            field=models.CharField(blank=True, default=None, max_length=313, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="sth_nd300_ris",
            field=models.CharField(blank=True, default=None, max_length=314, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="sth_nm",
            field=models.CharField(blank=True, default=None, max_length=315, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="sth_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=316, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="str_nd10",
            field=models.CharField(blank=True, default=None, max_length=273, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="str_nd10_ris",
            field=models.CharField(blank=True, default=None, max_length=274, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="str_nm",
            field=models.CharField(blank=True, default=None, max_length=275, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="str_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=276, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="sxt_nd1_2",
            field=models.CharField(blank=True, default=None, max_length=213, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="sxt_nd1_2_ris",
            field=models.CharField(blank=True, default=None, max_length=214, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="sxt_nm",
            field=models.CharField(blank=True, default=None, max_length=215, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="sxt_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=216, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="tcc_nd75",
            field=models.CharField(blank=True, default=None, max_length=285, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="tcc_nd75_ris",
            field=models.CharField(blank=True, default=None, max_length=286, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="tcc_nm",
            field=models.CharField(blank=True, default=None, max_length=287, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="tcc_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=288, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="tcy_nd30",
            field=models.CharField(blank=True, default=None, max_length=277, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="tcy_nd30_ris",
            field=models.CharField(blank=True, default=None, max_length=278, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="tcy_nm",
            field=models.CharField(blank=True, default=None, max_length=279, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="tcy_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="tic_nd75",
            field=models.CharField(blank=True, default=None, max_length=281, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="tic_nd75_ris",
            field=models.CharField(blank=True, default=None, max_length=282, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="tic_nm",
            field=models.CharField(blank=True, default=None, max_length=283, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="tic_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=284, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="tob_nd10",
            field=models.CharField(blank=True, default=None, max_length=289, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="tob_nd10_ris",
            field=models.CharField(blank=True, default=None, max_length=290, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="tob_nm",
            field=models.CharField(blank=True, default=None, max_length=291, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="tob_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=292, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="tzp_nd100",
            field=models.CharField(blank=True, default=None, max_length=305, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="tzp_nd100_ris",
            field=models.CharField(blank=True, default=None, max_length=306, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="tzp_nm",
            field=models.CharField(blank=True, default=None, max_length=307, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="tzp_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=308, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="van_nd30",
            field=models.CharField(blank=True, default=None, max_length=293, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="van_nd30_ris",
            field=models.CharField(blank=True, default=None, max_length=294, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="van_nm",
            field=models.CharField(blank=True, default=None, max_length=295, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="van_nm_ris",
            field=models.CharField(blank=True, default=None, max_length=296, null=True),
        ),
        migrations.AlterField(
            model_name="referreddb",
            name="ward",
            field=models.CharField(blank=True, default=None, max_length=113, null=True),
        ),
    ]
