# Generated by Django 4.2.7 on 2023-11-08 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("wgs_app", "0005_alter_referreddb_age_alter_referreddb_amc_nd20_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualifyr",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="qualifyr",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="referreddb",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="referreddb",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
