# Generated by Django 4.2.7 on 2023-11-08 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wgs_app", "0006_qualifyr_created_at_qualifyr_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualifyr",
            name="accession_no",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="wgs_app.referreddb",
            ),
        ),
        migrations.AlterField(
            model_name="qualifyr",
            name="sample_name",
            field=models.CharField(
                blank=True, default=None, max_length=100, null=True, unique=True
            ),
        ),
    ]
